// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dns_records.sql

package database

import (
	"context"
)

const createDNSRecord = `-- name: CreateDNSRecord :one
INSERT INTO dns_records (id, name, ttl, class, type, value, created_at, updated_at)
VALUES (
        gen_random_uuid(),$1, $2, $3, $4, $5, NOW(), NOW()
)
RETURNING id, name, ttl, class, type, value, created_at, updated_at
`

type CreateDNSRecordParams struct {
	Name  string
	Ttl   int32
	Class string
	Type  string
	Value string
}

func (q *Queries) CreateDNSRecord(ctx context.Context, arg CreateDNSRecordParams) (DnsRecord, error) {
	row := q.db.QueryRowContext(ctx, createDNSRecord,
		arg.Name,
		arg.Ttl,
		arg.Class,
		arg.Type,
		arg.Value,
	)
	var i DnsRecord
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ttl,
		&i.Class,
		&i.Type,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDNSRecordByName = `-- name: GetDNSRecordByName :many
SELECT id, name, ttl, class, type, value, created_at, updated_at FROM dns_records WHERE name = $1
`

func (q *Queries) GetDNSRecordByName(ctx context.Context, name string) ([]DnsRecord, error) {
	rows, err := q.db.QueryContext(ctx, getDNSRecordByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DnsRecord
	for rows.Next() {
		var i DnsRecord
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ttl,
			&i.Class,
			&i.Type,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDNSRecordByValue = `-- name: GetDNSRecordByValue :many
SELECT id, name, ttl, class, type, value, created_at, updated_at FROM dns_records WHERE value = $1
`

func (q *Queries) GetDNSRecordByValue(ctx context.Context, value string) ([]DnsRecord, error) {
	rows, err := q.db.QueryContext(ctx, getDNSRecordByValue, value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DnsRecord
	for rows.Next() {
		var i DnsRecord
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ttl,
			&i.Class,
			&i.Type,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDNSRecords = `-- name: GetDNSRecords :many
SELECT id, name, ttl, class, type, value, created_at, updated_at FROM dns_records
`

func (q *Queries) GetDNSRecords(ctx context.Context) ([]DnsRecord, error) {
	rows, err := q.db.QueryContext(ctx, getDNSRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DnsRecord
	for rows.Next() {
		var i DnsRecord
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ttl,
			&i.Class,
			&i.Type,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRecordByName = `-- name: RemoveRecordByName :exec
DELETE FROM dns_records WHERE name = $1
`

func (q *Queries) RemoveRecordByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, removeRecordByName, name)
	return err
}

const removeRecordByValue = `-- name: RemoveRecordByValue :exec
DELETE FROM dns_records WHERE value = $1
`

func (q *Queries) RemoveRecordByValue(ctx context.Context, value string) error {
	_, err := q.db.ExecContext(ctx, removeRecordByValue, value)
	return err
}

const removeRecords = `-- name: RemoveRecords :exec
DELETE FROM dns_records
`

func (q *Queries) RemoveRecords(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeRecords)
	return err
}
