// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
)

type DnsRecord struct {
	ID        uuid.UUID
	Name      string
	Ttl       int32
	Class     string
	Type      string
	Value     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
